version: '3.8'

volumes:
  mixpost_storage:
  mysql_data:

services:
  mixpost-mysql:
    image: mysql/mysql-server:8.0
    container_name: mixpost-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=mixpost
      - MYSQL_USER=mixpost
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  mixpost:
    image: inovector/mixpost-pro-team:latest
    container_name: mixpost
    restart: unless-stopped
    ports:
      - "9000:80"
    environment:
      # License
      - LICENSE_KEY=yoeya4oEyrmiEEDKZGr2RtMTJVQJhBkpaPuT8EXAL1NOsZVUEFrUMzSxt5Vy7i1J
      
      # Application
      - APP_NAME=Mixpost
      - APP_KEY=base64:mSkK0ldNzh0XYDc0QiCkEGDcvbTTVbIfY3m3UssGvAU=
      - APP_URL=https://social.everydaycreator.org
      - APP_DOMAIN=social.everydaycreator.org
      - SESSION_DOMAIN=.everydaycreator.org
      - SSL_EMAIL=${LETSENCRYPT_EMAIL:-admin@everydaycreator.org}
      
      # Database
      - DB_DATABASE=mixpost
      - DB_USERNAME=mixpost
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=mixpost-mysql
      
      # Redis
      - REDIS_HOST=valkey
      - REDIS_PORT=6379
      
      # Mail
      - MAIL_MAILER=smtp
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS}
      - MAIL_FROM_NAME=${MAIL_FROM_NAME}
      
      # Logging
      - LOG_CHANNEL=stack
      
      # Queue & Session
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis
      - CACHE_DRIVER=redis
    depends_on:
      - mixpost-mysql
    volumes:
      - mixpost_storage:/var/www/html/storage/app